# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

# This configuration based on:
# https://github.com/cookiecutter/cookiecutter/blob/5e65edf4c340993f462ddeaf44f99eb6f9da66f9/appveyor.yml

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      TOX_ENV: "test-py36,codecov"

    - PYTHON: "C:\\Python37-x64"
      TOX_ENV: "test-py37,codecov"

    - PYTHON: "C:\\Python38-x64"
      TOX_ENV: "test-py38,codecov"


init:
  - set OS=WINDOWS
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""
  - "%PYTHON%/python -V"
  - "%PYTHON%/python -c \"import struct;print(8 * struct.calcsize(\'P\'))\""
  - set

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install -U --force-reinstall tox virtualenv wheel"


build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/Scripts/tox -e %TOX_ENV%"

artifacts:
  - path: dist\*
